# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
    ]
